name: ninta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.0.0
  permission_handler: ^11.3.0
  provider: ^6.1.1
  go_router: ^13.2.0
  transparent_image: ^2.0.1
  intl: ^0.19.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  path_provider: ^2.1.5
  extended_image: ^10.0.1
  photo_manager_image_provider: ^2.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_map_heatmap: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
