name: fl_training_plugin
description: A Flutter plugin for on-device Federated Learning training using PyTorch Mobile.
version: 0.0.1
homepage: https://example.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fl_training_plugin
        pluginClass: FlTrainingPlugin
      ios:
        pluginClass: FlTrainingPlugin
      windows:
        pluginClass: FlTrainingPluginCApi
